### ISSUE TITLE
Remove Underlined

### ISSUE THREAD

**Issue by scinfu** [AliSoftware/OHAttributedStringAdditions#5]
```
- (void)setTextUnderlined:(BOOL)underlined;
- (void)setTextUnderlined:(BOOL)underlined range:(NSRange)range;
```

This methods don't work , i can't remove underline and the color of the link is blue but i set red .
Any solution ?

Exemple  , i override setTex of UILabel

```
- (void)setText:(NSString *)text
{
    NSMutableAttributedString* attrStr = [[NSMutableAttributedString alloc]initWithString:text];


    NSString* pattern = @"\\B#\\w+";
    NSRegularExpression* hashTagRegExp = [NSRegularExpression regularExpressionWithPattern:pattern options:0 error:nil];
    NSString* str = attrStr.string; // The plain text we will iterate over

    [hashTagRegExp enumerateMatchesInString:str options:0 range:NSMakeRange(0,str.length)
                                 usingBlock:^(NSTextCheckingResult *match, NSMatchingFlags flags, BOOL *stop)
     {
         // For each "#xxx" hashtag found, add a custom link:
         NSString* tag = [[str substringWithRange:match.range] substringFromIndex:1]; // get the tag without the "#"
         NSString* linkURLString = [NSString stringWithFormat:@"tag:%@", tag]; // build a "tag:xxx" link
         [attrStr setURL:[NSURL URLWithString:linkURLString] range:match.range]; // add the URL
         [attrStr setTextColor:[UIColor redColor] range:match.range]; // also, color it blue
         [attrStr setTextUnderlined:NO range:match.range];

     }];

    self.attributedText = attrStr ;
}
```

**Comment by AliSoftware** [comment]
That is not an issue with `OHAttributedStringAdditions` itself but is due to the behavior of `UILabel` (and its associated `NSLayoutManager`) that **discards the text color and underline state for links**, overriding them with blue, underlined, whatever the `NSAttributedString` attributes for `NSForegroundColorAttributeName` and `NSUnderlineStyleAttributeName` are. So that's an Apple behavior (bug?).
- If you remove your link (don't call `setURL:range:`) then you will see that your text will be red and not-underlined. That proves that this is not an issue with my `setTextUnderlined` _per se_, but by the way `UILabel` displays links.
- If you use an `UITextView` to display your `NSAttributedString`, you can use its `linkTextAttributes` property to configure how the links are to be rendered, especially their foreground color and underline style (defaults to blue and underline, as stated in this property's documentation). That's probably the easiest way to solve your problem, migrating from `UILabel` to `UITextView` and customize your `UITextView` properties so that it looks like an `UILabel`, especially `editable = NO`, `textContainerInset = UIEdgeInsetsZero` and `lintTextAttributes` to your liking.
- If you still really need to use an `UILabel`, [read Cocoanetics's article on the subject](https://www.cocoanetics.com/2015/03/customizing-uilabel-hyperlinks/) which explains why this happens and how to workaround Apple's choice of overriding the links color & underline style. But you can see in that article that the fact that Apple didn't make `UILabel` expose its `NSLayoutManager` as a public property makes it quite hard to do, as described in this article. That's why using an `UITextView` to customize those stuff more is way easier, because `UITextView` exposes a lot more stuff, like `linkTextAttributes` but also its `layoutManager` property.
